version: '2'

volumes:
  db_data:
    driver: local
  app_data:
    driver: local

services:
  postgresql:
    image: mdillon/postgis:9.5
    volumes:
      - db_data:/var/lib/postgresql/data

  skygear-server:
    image: quay.io/skygeario/skygear-server:v0.21.1
    ports:
      - "3000:3000"
    links:
      - postgresql
    command: skygear-server
    environment:
      DATABASE_URL: postgresql://postgres:@postgresql/postgres?sslmode=disable
      API_KEY: cmsdidntworkforme
      MASTER_KEY: cmsdidntworkforme
      APP_NAME: cmsdidntworkforme
      TOKEN_STORE: jwt
      TOKEN_STORE_SECRET: cmsdidntworkforme
      PLUGINS: 'PYTHON,NODE'
      PYTHON_TRANSPORT: zmq
      PYTHON_ARGS: 'tcp://*:5555'
      NODE_TRANSPORT: http
      NODE_PATH: http://node:9000

  python:
    image: quay.io/skygeario/py-skygear:v0.21.0
    command: py-skygear __init__.py
    volumes:
      - ./python/__init__.py:/usr/src/app/__init__.py
    links:
      - skygear-server
    environment:
      DATABASE_URL: postgresql://postgres:@postgresql/postgres?sslmode=disable
      API_KEY: cmsdidntworkforme
      MASTER_KEY: cmsdidntworkforme
      APP_NAME: cmsdidntworkforme
      SKYGEAR_ADDRESS: tcp://skygear-server:5555
      PUBSUB_URL: ws://skygear-server:3000/pubsub
      SERVE_STATIC_ASSETS: 'false'

  node:
    build:
      context: ./cms
    environment:
      DATABASE_URL: postgresql://postgres:@postgresql/postgres?sslmode=disable
      API_KEY: cmsdidntworkforme
      MASTER_KEY: cmsdidntworkforme
      APP_NAME: cmsdidntworkforme
      PUBSUB_URL: ws://skygear-server:3000/pubsub
      SERVE_STATIC_ASSETS: 'true'
      SKYGEAR_CMS_STATIC_ASSETS_PREFIX: '/static/cms/'
